version: "3.1"

services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dist/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Note
      POSTGRES_PASSWORD: Love1234
      POSTGRES_DB: ParkingDB

volumes:
  pgdata:
